"""Publish a Horizon daily summary to a WeChat Official Account.

The script reads the Markdown summary generated by Horizon and creates a
WeChat draft article. Set WECHAT_PUBLISH_MODE=publish to submit the draft
through WeChat's free-publish API after creation.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any

import httpx
import markdown
from bs4 import BeautifulSoup


API_BASE = "https://api.weixin.qq.com/cgi-bin"


@dataclass
class WeChatConfig:
    app_id: str
    app_secret: str
    thumb_media_id: str
    author: str
    publish_mode: str
    source_url: str


def _env(name: str, default: str | None = None, required: bool = False) -> str:
    value = os.getenv(name, default)
    if required and not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value or ""


def load_config() -> WeChatConfig:
    mode = _env("WECHAT_PUBLISH_MODE", "draft").strip().lower()
    allowed_modes = {"draft", "publish"}
    if mode not in allowed_modes:
        raise RuntimeError(
            f"WECHAT_PUBLISH_MODE must be one of {sorted(allowed_modes)}, got {mode!r}"
        )

    return WeChatConfig(
        app_id=_env("WECHAT_APP_ID", required=True),
        app_secret=_env("WECHAT_APP_SECRET", required=True),
        thumb_media_id=_env("WECHAT_THUMB_MEDIA_ID", required=True),
        author=_env("WECHAT_AUTHOR", "Horizon"),
        publish_mode=mode,
        source_url=_env("WECHAT_CONTENT_SOURCE_URL", ""),
    )


def strip_front_matter(markdown_text: str) -> str:
    if markdown_text.startswith("---\n"):
        parts = markdown_text.split("---\n", 2)
        if len(parts) == 3:
            return parts[2].lstrip()
    return markdown_text


def plain_text(markdown_text: str) -> str:
    html = markdown.markdown(markdown_text)
    soup = BeautifulSoup(html, "html.parser")
    text = soup.get_text(" ", strip=True)
    return re.sub(r"\s+", " ", text).strip()


def clamp(value: str, limit: int) -> str:
    value = re.sub(r"\s+", " ", value).strip()
    if len(value) <= limit:
        return value
    return value[: limit - 3].rstrip() + "..."


def extract_title(markdown_text: str, date: str) -> tuple[str, str]:
    lines = markdown_text.splitlines()
    for index, line in enumerate(lines):
        if line.startswith("# "):
            title = clamp(line[2:].strip(), 64)
            body = "\n".join(lines[:index] + lines[index + 1 :]).strip()
            return title, body
    return f"Horizon Daily News {date}", markdown_text


def build_article_html(markdown_text: str) -> str:
    body_html = markdown.markdown(
        markdown_text,
        extensions=["extra", "sane_lists", "tables"],
        output_format="html5",
    )
    return f"""
<section style="font-size:16px;line-height:1.75;color:#1f2937;">
  <p style="color:#64748b;margin:0 0 16px 0;">Generated by Horizon.</p>
  {body_html}
</section>
""".strip()


def find_summary(summary_dir: Path, date: str | None, lang: str) -> tuple[Path, str]:
    if date:
        path = summary_dir / f"horizon-{date}-{lang}.md"
        if not path.exists():
            raise FileNotFoundError(f"Summary not found: {path}")
        return path, date

    candidates = sorted(summary_dir.glob(f"horizon-*-{lang}.md"), reverse=True)
    if not candidates:
        raise FileNotFoundError(f"No Horizon {lang!r} summaries found in {summary_dir}")

    latest = candidates[0]
    match = re.search(r"horizon-(\d{4}-\d{2}-\d{2})-[a-z]+\.md$", latest.name)
    inferred_date = match.group(1) if match else datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return latest, inferred_date


def wechat_post(client: httpx.Client, url: str, payload: dict[str, Any]) -> dict[str, Any]:
    response = client.post(url, json=payload)
    response.raise_for_status()
    data = response.json()
    errcode = data.get("errcode", 0)
    if errcode not in (0, "0"):
        raise RuntimeError(f"WeChat API error {errcode}: {data.get('errmsg', data)}")
    return data


def get_access_token(client: httpx.Client, config: WeChatConfig) -> str:
    response = client.get(
        f"{API_BASE}/token",
        params={
            "grant_type": "client_credential",
            "appid": config.app_id,
            "secret": config.app_secret,
        },
    )
    response.raise_for_status()
    data = response.json()
    token = data.get("access_token")
    if not token:
        raise RuntimeError(f"Could not get WeChat access token: {data}")
    return token


def create_draft(
    client: httpx.Client,
    token: str,
    config: WeChatConfig,
    title: str,
    digest: str,
    html_content: str,
) -> str:
    payload = {
        "articles": [
            {
                "title": title,
                "author": config.author,
                "digest": digest,
                "content": html_content,
                "content_source_url": config.source_url,
                "thumb_media_id": config.thumb_media_id,
                "need_open_comment": 0,
                "only_fans_can_comment": 0,
            }
        ]
    }
    data = wechat_post(client, f"{API_BASE}/draft/add?access_token={token}", payload)
    media_id = data.get("media_id")
    if not media_id:
        raise RuntimeError(f"WeChat draft response did not include media_id: {data}")
    return media_id


def submit_publish(client: httpx.Client, token: str, media_id: str) -> str:
    data = wechat_post(
        client,
        f"{API_BASE}/freepublish/submit?access_token={token}",
        {"media_id": media_id},
    )
    publish_id = data.get("publish_id", "")
    return str(publish_id)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Publish the latest Horizon summary to a WeChat Official Account."
    )
    parser.add_argument("--date", default=None, help="Summary date, e.g. 2026-06-13")
    parser.add_argument("--lang", default=os.getenv("WECHAT_LANG", "zh"))
    parser.add_argument("--summary-dir", default="data/summaries")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    config = load_config()
    summary_path, summary_date = find_summary(Path(args.summary_dir), args.date, args.lang)
    raw_markdown = strip_front_matter(summary_path.read_text(encoding="utf-8"))
    title, body_markdown = extract_title(raw_markdown, summary_date)
    digest = clamp(_env("WECHAT_DIGEST", "") or plain_text(body_markdown), 120)
    html_content = build_article_html(body_markdown)

    if args.dry_run or _env("WECHAT_DRY_RUN", "").lower() in {"1", "true", "yes"}:
        print(f"Dry run: {summary_path}")
        print(f"Title: {title}")
        print(f"Digest: {digest}")
        print(f"HTML chars: {len(html_content)}")
        return 0

    with httpx.Client(timeout=30.0) as client:
        token = get_access_token(client, config)
        media_id = create_draft(client, token, config, title, digest, html_content)
        print(f"Created WeChat draft: {escape(media_id)}")

        if config.publish_mode == "publish":
            publish_id = submit_publish(client, token, media_id)
            print(f"Submitted WeChat publish task: {escape(publish_id)}")
        else:
            print("WECHAT_PUBLISH_MODE=draft, leaving article in draft box.")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"publish_wechat.py failed: {exc}", file=sys.stderr)
        raise SystemExit(1)
